# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(db_column='name', default='', max_length=255)),
                ('_notes', models.CharField(db_column='notes', default='', max_length=1000)),
                ('_creation_date', models.DateField(db_column='creation_date', default=django.utils.timezone.now)),
            ],
        ),
    ]
