# Generated by Django 2.0.1 on 2018-05-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMapper',
            fields=[
                ('name', models.CharField(default='', max_length=255)),
                ('notes', models.CharField(default='', max_length=1000)),
                ('uid', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Items',
                'verbose_name': 'Item',
            },
        ),
        migrations.CreateModel(
            name='WarehouseItemMapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'WarehouseItems',
                'verbose_name': 'WarehouseItem',
            },
        ),
        migrations.CreateModel(
            name='WarehouseMapper',
            fields=[
                ('name', models.CharField(default='', max_length=255)),
                ('uid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('items', models.ManyToManyField(to='warehouse_management.WarehouseItemMapper')),
            ],
            options={
                'verbose_name_plural': 'Warehouses',
                'verbose_name': 'Warehouse',
            },
        ),
    ]
