# Generated by Django 2.0.1 on 2018-05-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseitemmapper',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
