# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse_management', '0002_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(db_column='name', default='', max_length=255)),
                ('_notes', models.CharField(db_column='notes', default='', max_length=1000)),
            ],
        ),
    ]
