# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0004_auto_20171221_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmapper',
            name='id',
        ),
        migrations.AddField(
            model_name='itemmapper',
            name='uid',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
