# Generated by Django 2.0.1 on 2018-03-10 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0005_auto_20171222_2018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemmapper',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
    ]
